brew 'hub'
brew 'lv'
brew 'fontforge'

brew 'lua'
brew 'pyenv'
brew 'nodenv'
brew 'rbenv'
brew 'ruby-build'

brew 'imagemagick'
brew 'memcached'
brew 'mysql'
brew 'phantomjs'
brew 'redis'
brew 'wget'
brew 'qt'

tap 'caskroom/cask'

cask 'adobe-reader'
cask 'atom'
cask 'evernote'
cask 'dropbox'
cask 'firefox'
cask 'fluid'
cask 'gas-mask'
cask 'github-desktop'
cask 'googleappengine'
cask 'google-chrome'
cask 'google-cloud-sdk'
cask 'google-drive'
cask 'google-japanese-ime'
cask 'google-web-designer'
cask 'heroku-toolbelt'
cask 'hockey'
cask 'iterm2'
cask 'java'
cask 'libreoffice'
cask 'licecap'
cask 'postgres'
cask 'rstudio'
cask 'silverlight'
cask 'skype'
cask 'splashtop-streamer'
cask 'vagrant'
cask 'virtualbox'
cask 'visual-studio-code'
cask 'xquartz'

tap 'caskroom/fonts'

cask 'font-inconsolata-dz-for-powerline'
