brew 'openssl'

brew 'hub'
brew 'lv'
brew 'fontforge'

brew 'cmake'
brew 'lua'
brew 'nvm'
brew 'go'
brew 'rbenv'
brew 'ruby-build'
brew 'yarn'

brew 'awscli'
brew 'awsebcli'
brew 'ctags'
brew 'direnv'
brew 'flow'
brew 'ffmpeg'
brew 'imagemagick'
brew 'memcached'
brew 'mysql'
brew 'packer'
brew 'phantomjs'
brew 'pow'
brew 'redis'
brew 'terraform'
brew 'the_silver_searcher'
brew 'wget'
brew 'watchman'
brew 'qt'

tap 'caskroom/cask'

cask 'adobe-reader'
cask 'atom'
cask 'chefdk'
cask 'evernote'
cask 'dockertoolbox'
cask 'dropbox'
cask 'firefox'
cask 'fluid'
cask 'gas-mask'
cask 'github-desktop'
cask 'googleappengine'
cask 'google-chrome'
cask 'google-cloud-sdk'
cask 'google-drive'
cask 'google-japanese-ime'
cask 'google-web-designer'
cask 'heroku-toolbelt'
cask 'hockey'
cask 'iterm2'
cask 'java'
cask 'kindle'
cask 'libreoffice'
cask 'licecap'
cask 'mysqlworkbench'
cask 'near-lock'
cask 'postgres'
cask 'rstudio'
cask 'silverlight'
cask 'skype'
cask 'splashtop-streamer'
cask 'vagrant'
cask 'vagrant-manager'
cask 'virtualbox'
cask 'visual-studio-code'
cask 'xquartz'

tap 'caskroom/fonts'

cask 'font-inconsolata-dz-for-powerline'
