brew 'openssl'
brew 'readline'
brew 'libmagic'
brew 'libpq'

brew 'cmake'

brew 'asdf'

brew 'gcc'
brew 'lua'

brew 'atlas'
brew 'awscli'
brew 'chrome-devtools-mcp'
brew 'cloud-sql-proxy'
brew 'coreutils'
brew 'direnv'
brew 'flow'
brew 'fontforge'
brew 'fswatch'
brew 'gh'
brew 'git-lfs'
brew 'git-secrets'
brew 'gnu-sed'
brew 'gpg'
brew 'graphviz'
brew 'httping'
brew 'jq'
brew 'lv'
brew 'mas'
brew 'mecab'
brew 'mecab-ipadic'
brew 'mysql'
brew 'openapi-generator'
brew 'packer'
brew 'peco'
brew 'python-tk'
brew 'qt'
brew 'stripe-cli'
brew 'telnet'
brew 'terminal-notifier'
brew 'the_silver_searcher'
brew 'tig'
brew 'tmux'
brew 'tree'
brew 'typescript-language-server'
brew 'unison'
brew 'uv'
brew 'vim'
brew 'wget'
brew 'watchman'

mas 'Fotor',             id: 503039729
mas 'Keynote',           id: 409183694
mas 'Slack',             id: 803453959
mas 'WeChat',            id: 836500024
mas 'Xcode',             id: 497799835

tap 'cesanta/mos'
brew 'mos'

tap 'heroku/brew'
brew 'heroku'

cask 'android-platform-tools'
cask 'android-ndk'
cask 'android-studio'
cask 'arduino'
cask 'chromedriver'
cask 'claude'
cask 'claude-code'
cask 'codex'
cask 'codex-app'
cask 'cursor'
cask 'docker-desktop'
cask 'dropbox'
cask 'figma'
cask 'firefox'
cask 'font-inconsolata-nerd-font'
cask 'gas-mask'
cask 'google-chrome'
cask 'gcloud-cli'
cask 'ghostty'
cask 'google-drive'
cask 'kindle'
cask 'ngrok'
cask 'session-manager-plugin'
cask 'windows-app'
cask 'xquartz'
