set-option -g default-terminal "tmux-256color"
set-option -sa terminal-features ",xterm-ghostty:RGB"
set-option -sa terminal-overrides ",xterm-ghostty:Tc"
set-option -g mouse on

# vi コピーモード
set-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"

# ステータスバー（Wombat カラー）
set-option -g status-style "bg=#171717,fg=#dedacf"
set-option -g window-status-current-style "bg=#453b39,fg=#ebd99c"
set-option -g status-right ""
